[features]
seeds = false
skip-lint = false
[programs.localnet]
crypto_wedding = "sRT1XWM1ZoPVaBzsvjmCUfjGxBGbNAWGdRc8V15t7aQ"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./external_progs/token_metadata.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/codylamson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/rings.ts"
